name: Deploy master branch dev

on:
  push:
    branches:
      - master

defaults:
  run:
    shell: bash

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 'Setup pnpm'
        uses: pnpm/action-setup@v2.2.4
        with:
          version: 'latest'

      - name: 'Setup Node.js'
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          cache: pnpm

      - name: 'Install Dependencies'
        run: pnpm install

      - name: 'Build'
        run: pnpm build

      - name: 'Deploy'
        uses: serverless/github-action@v3.1
        with:
          args: deploy --stage dev
        env:
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
          PGHOST: ${{ secrets.PGHOST }}
          PGUSER: ${{ secrets.PGUSER }}
          PGDATABASE: ${{ secrets.PGDATABASE }}
          PGPASSWORD: ${{ secrets.PGPASSWORD }}
          PGPORT: ${{ secrets.PGPORT }}
          CUSTOM_PROVIDER: ${{ secrets.CUSTOM_PROVIDER }}
          LLAMANODES_API_KEY: ${{ secrets.LLAMANODES_API_KEY }}
          ARBITRUM_RPC: ${{ secrets.ARBITRUM_RPC }}
          OPTIMISM_RPC: ${{ secrets.OPTIMISM_RPC }}
